apiVersion: v1
kind: Secret
metadata:
  name: bite-brew-secrets
  namespace: bite-brew-prod
type: Opaque
stringData:
  DATABASE_URL: replace-me
  REDIS_URL: replace-me
  JWT_SECRET_TOKEN: replace-me
  ACCESS_TOKEN_SECRET: replace-me
  REFRESH_TOKEN_SECRET: replace-me
  SMTP_HOST: replace-me
  SMTP_PORT: '587'
  SMTP_USER: replace-me
  SMTP_PASS: replace-me
  CLOUDINARY_CLOUD_NAME: replace-me
  CLOUDINARY_API_KEY: replace-me
  CLOUDINARY_API_SECRET: replace-me
  FRONTEND_URL: https://your-frontend.example.com
